title: Blog
description: Personal blog/documentation website to help me keep track of things.
author: Mohd Abbas Zaidi
avatar: /logo.png
email: mzaidi59@gmail.com
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://mzaidi59.github.io" # the base hostname & protocol for your site, e.g. http://example.com

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 10

# Uncomment the below line and set the tracking ID for enabling Google Analytics
# 
# google_analytics: 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

# Jekyll SEO Tag (Optional)
# =========================
twitter:
  username: mabbas7861
  card: summary
logo: logo.png
skin: sunset
social:
  name: Mohd Abbas Zaidi
  links:
    - https://twitter.com/mabbas7861
    - https://github.com/mzaidi59
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: en
